### ISSUE TITLE
Separar e documentar sobrescrita de classes de cores

### ISSUE THREAD

**Issue by ericmdantas** [dsn-nimbus/alterdata-material-design#4]
Hoje os exemplos tem algumas cores pré definidas (maioria em cinza).
Devemos ter uma forma simples de um sistema poder sobrescrever estas cores.

Por exemplo, temos:

``` css
/*alt-cores.css*/

.alt-cor-principal {
  color: #fff;
  background-color: #000;
}
```

Deve ser simples e bem documentado que tudo que o usuário deve fazer é:

``` css
/*qualquer-nome-de-css-por-sistema-css*/

.alt-cor-principal {
  color: #red;
  background-color: #blue;
}
```

A separação do css para `alt-cores.css`  já ajuda, mas a documentação, assim como um exemplo onde as cores são sobrescritas, tem que ser criada.
